### ISSUE TITLE
b64encode error 

### ISSUE THREAD

**Issue by jakekn1** [cohesity/cohesity-vcd-extension#3]
C:\Users\username\AppData\Local\Programs\Python\Python38>python.exe deploy.py deploy
2020-06-12 11:07:34,990 DEBUG Added a stderr logging handler to logger: urllib3
Traceback (most recent call last):
  File "deploy.py", line 206, in <module>
    ui = UiPlugin(cfg['vcduri'], cfg['username'],
  File "deploy.py", line 21, in __init__
    self.getToken(username, org, password)
  File "deploy.py", line 48, in getToken
    auth='Basic %s' % base64.b64encode(
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

**Comment by shubhamkr-cohesity** [comment]
@jakekn1 
Thanks for bringing this. This has been fixed in v1.5.0.
